# Generated by Django 3.2.9 on 2021-12-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('time', models.TimeField(auto_now_add=True)),
                ('joyi', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Bajarilmadi', 'Bajarilmadi'), ('Bajarildi', 'Bajarildi')], max_length=20)),
            ],
        ),
    ]
